### ISSUE TITLE
ダウンロードしている郵便番号ファイルのURLが変更になったためDeploy処理に失敗している

### ISSUE THREAD

**Issue by pchw** [tokyootakumode/postal-code-api#19]
https://github.com/tokyootakumode/postal-code-api/actions/runs/5500501122/jobs/10023447741

```
Run npm run build

> postal-code-api@1.0.0 build
> gulp

[15:02:0[4](https://github.com/tokyootakumode/postal-code-api/actions/runs/5500501122/jobs/10023447741#step:6:5)] Using gulpfile ~/work/postal-code-api/postal-code-api/gulpfile.js
[1[5](https://github.com/tokyootakumode/postal-code-api/actions/runs/5500501122/jobs/10023447741#step:6:6):02:04] Starting 'default'...
[15:02:04] Starting 'v1'...
[15:02:04] Starting 'download'...
[gulp] Downloading http://www.post.japanpost.jp/zipcode/dl/roman/ken_all_rome.zip... Done
[gulp] Downloading http://www.post.japanpost.jp/zipcode/dl/jigyosyo/zip/jigyosyo.zip... Done
[15:02:08] Finished 'download' after 4.39 s
[15:02:08] Starting '<anonymous>'...
[15:02:08] '<anonymous>' errored after 13 ms
[15:02:08] Error: File not found with singular glob: /home/runner/work/postal-code-api/postal-code-api/lib/api/KEN_ALL_ROME.csv (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/home/runner/work/postal-code-api/postal-code-api/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (node:events:[6](https://github.com/tokyootakumode/postal-code-api/actions/runs/5500501122/jobs/10023447741#step:6:7)28:26)
    at Glob.emit (node:events:513:28)
    at Glob.emit (node:domain:489:12)
    at Glob._finish (/home/runner/work/postal-code-api/postal-code-api/node_modules/glob/glob.js:194:8)
    at done (/home/runner/work/postal-code-api/postal-code-api/node_modules/glob/glob.js:1[7](https://github.com/tokyootakumode/postal-code-api/actions/runs/5500501122/jobs/10023447741#step:6:8)9:14)
    at Glob._processSimple2 (/home/runner/work/postal-code-api/postal-code-api/node_modules/glob/glob.js:6[8](https://github.com/tokyootakumode/postal-code-api/actions/runs/5500501122/jobs/10023447741#step:6:9)5:12)
    at /home/runner/work/postal-code-api/postal-code-api/node_modules/glob/glob.js:673:10
    at Glob._stat2 (/home/runner/work/postal-code-api/postal-code-api/node_modules/glob/glob.js:76[9](https://github.com/tokyootakumode/postal-code-api/actions/runs/5500501122/jobs/10023447741#step:6:10):[12](https://github.com/tokyootakumode/postal-code-api/actions/runs/5500501122/jobs/10023447741#step:6:13))
    at lstatcb_ (/home/runner/work/postal-code-api/postal-code-api/node_modules/glob/glob.js:761:12)
[[15](https://github.com/tokyootakumode/postal-code-api/actions/runs/5500501122/jobs/10023447741#step:6:16):02:08] 'v1' errored after 4.41 s
[15:02:08] 'default' errored after 4.41 s
Error: Process completed with exit code 1.
```

https://github.com/tokyootakumode/postal-code-api/blob/fcbb1880f482c217bb53fa663f4b1d9099caea43/gulpfile.js#L13-L16
となっているが，
```
https://www.post.japanpost.jp/zipcode/dl/roman/KEN_ALL_ROME.zip
https://www.post.japanpost.jp/zipcode/dl/jigyosyo/zip/jigyosyo.zip
```
へ変更となっている

**Comment by pchw** [comment]
まだ失敗しているためreopen

```
> postal-code-api@1.0.0 build
> gulp

[15:01:5[6](https://github.com/tokyootakumode/postal-code-api/actions/runs/5544690057/jobs/10122519754#step:6:7)] Using gulpfile ~/work/postal-code-api/postal-code-api/gulpfile.js
[15:01:56] Starting 'default'...
[15:01:56] Starting 'v1'...
[15:01:56] Starting 'download'...
[gulp] Downloading https://www.post.japanpost.jp/zipcode/dl/roman/KEN_ALL_ROME.zip... 0.30[7](https://github.com/tokyootakumode/postal-code-api/actions/runs/5544690057/jobs/10122519754#step:6:8)1107[8](https://github.com/tokyootakumode/postal-code-api/actions/runs/5544690057/jobs/10122519754#step:6:9)133[9](https://github.com/tokyootakumode/postal-code-api/actions/runs/5544690057/jobs/10122519754#step:6:10)2632% 0.990421316411789% Done
[gulp] Downloading https://www.post.japanpost.jp/zipcode/dl/jigyosyo/zip/jigyosyo.zip... 0.474838[10](https://github.com/tokyootakumode/postal-code-api/actions/runs/5544690057/jobs/10122519754#step:6:11)3520569% Done
[15:02:03] Finished 'download' after 6.67 s
[15:02:03] Starting '<anonymous>'...
[15:02:03] '<anonymous>' errored after [11](https://github.com/tokyootakumode/postal-code-api/actions/runs/5544690057/jobs/10122519754#step:6:12) ms
[15:02:03] Error: File not found with singular glob: /home/runner/work/postal-code-api/postal-code-api/lib/api/KEN_ALL_ROME.csv (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/home/runner/work/postal-code-api/postal-code-api/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (node:events:628:26)
    at Glob.emit (node:events:513:28)
    at Glob.emit (node:domain:489:[12](https://github.com/tokyootakumode/postal-code-api/actions/runs/5544690057/jobs/10122519754#step:6:13))
    at Glob._finish (/home/runner/work/postal-code-api/postal-code-api/node_modules/glob/glob.js:194:8)
    at done (/home/runner/work/postal-code-api/postal-code-api/node_modules/glob/glob.js:179:[14](https://github.com/tokyootakumode/postal-code-api/actions/runs/5544690057/jobs/10122519754#step:6:15))
    at Glob._processSimple2 (/home/runner/work/postal-code-api/postal-code-api/node_modules/glob/glob.js:685:12)
    at /home/runner/work/postal-code-api/postal-code-api/node_modules/glob/glob.js:673:10
    at Glob._stat2 (/home/runner/work/postal-code-api/postal-code-api/node_modules/glob/glob.js:769:12)
    at lstatcb_ (/home/runner/work/postal-code-api/postal-code-api/node_modules/glob/glob.js:761:12)
[[15](https://github.com/tokyootakumode/postal-code-api/actions/runs/5544690057/jobs/10122519754#step:6:16):02:03] 'v1' errored after 6.68 s
[15:02:03] 'default' errored after 6.68 s
Error: Process completed with exit code 1.
```
